### ISSUE TITLE
作弊hi

### ISSUE THREAD

**Issue by RockerFlower** [xiangtailiang/FakeGPS#2]
# 码农的事怎么能叫作弊呢

请看一下 Teams of Service 先哦: [https://www.nianticlabs.com/terms/pokemongo/en](url)
看过还坚持“开源”、“分享”的话只能…

**Comment by xiangtailiang** [comment]
这只是一个工具，至于用来测试地址位置还是用来玩游戏，这个只能看用户使用了。
建议文明游戏，反对cheating。(^__^)

**Comment by RockerFlower** [comment]
问你支持不支持 cheating，你当然不能说支持，但 README 里完全就是在说用这个可以玩 Pokémon Go 啊大家快来玩啊。还有包名用 tencent 没问题吗？(^__^)

**Comment by xiangtailiang** [comment]
嗯，cheating行为不值得提倡，我已经把readme里面有关pokemon的都删掉了（截图就留着当做纪念）。
还是让FakeGPS回归工具本身吧。
包名已经修改了，多谢提醒。

**Comment by chchuj** [comment]
技术本身并不可耻。----王欣

**Comment by RockerFlower** [comment]
@chchuj 咦，您也玩 Ingress？用到啥技术了？
