### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by WANG529** [xiangtailiang/FakeGPS#6]
请问您的app是怎么用的？我在更改了坐标之后，用高德地图测试，发现还是我的实际定位。

**Comment by chenjunqi** [comment]
1. 我使用CoolPad 大神F1 （已Root）。
2. `mount -o remount,rw /dev/block/mmcblk0p12 /system`，重新`mount`查看`/dev/block/mmcblk0p12 /system ext4 rw,relatime,user_xattr,barrier=1,nodelalloc,data=ordered 0 0`
3. 修改`/system/app`权限为777
4. 以系统应用方式安装，`adb push FakeGPS.apk /system/app/FakeGps.apk`  
5. 打开开发者模式：
   > \* 依次关闭_允许模拟位置选项_。
   > \* 保持_Wi-Fi开启_。
   > \* 打开位置定位服务（酷派的定位设置），关闭AGPS（使用流量辅助定位），关闭使用Wi-Fi定位选项。
   > \* 酷派机器未安装SIM卡。

## **打开高德地图，定位地点仍然是真实的地点。**Why?我的想法，
- 没有安装SIM卡，就没有Cellid（排除通过基站定位）
- GPS信息应该已经伪造，手柄窗口已经显示，并且锁定了指定的经纬度（算是伪造成功了吧？）
- Wi-Fi已连接，并且周边Wi-Fi非常多（难不成因为周边Wi-Fi都是真实的，所以比对Wi-Fi的SSID得到的位置？）

**Comment by xiangtailiang** [comment]
有可能是wifi辅助定位的问题。有没有仅用GPS的选项？有的话仅仅用gps试试。
