### ISSUE TITLE
可以说一下这个项目的核心技术吗？

### ISSUE THREAD

**Issue by shatian114** [xiangtailiang/FakeGPS#7]
我用mocklocation模拟位置，把gps的经度和纬度都写进去了，读出来的也是我写进去的数，但是百度地图和微信的位置还是没变

**Comment by xiangtailiang** [comment]
通过hook系统的服务，强制写入mock GPS信息，如果用系统API来获取地理位，读到的是我们写入的信息，但微信和百度地图还用了自己的一些手段，不仅仅是系统的API。

**Comment by shatian114** [comment]
谢谢，主要还是不明白“自己的一些手段”是什么技术？

**Comment by xiangtailiang** [comment]
百度地图和腾讯地图为了更低功耗和更快定位，会优先使用网络定位，当达到一定精度后，连GPS都不需要读取，而FakeGPS改变的是系统API的GPS位置数据，没有被百度地图和腾讯地图使用到。

**Comment by imtypist** [comment]
那应该也可以hook一下网络相关的服务来更改网络定位吧？

**Comment by shatian114** [comment]
直接把网络定位的相关返回hook成null，让他们强制使用gps

**Comment by Jsharkc** [comment]
@shatian114 Hi，请问你实现了把网络定位的相关返回 hook 成 null 了吗

**Comment by shatian114** [comment]
> @shatian114 Hi，请问你实现了把网络定位的相关返回 hook 成 null 了吗

这只是我的思路，具体没有在代码上测试

**Comment by Jsharkc** [comment]
> > @shatian114 Hi，请问你实现了把网络定位的相关返回 hook 成 null 了吗
> 
> 这只是我的思路，具体没有在代码上测试

好的，蟹蟹
