### ISSUE TITLE
根据你的代码，自己写的有点问题，cannot be cast to

### ISSUE THREAD

**Issue by shatian114** [xiangtailiang/FakeGPS#9]
android.location.ILocationManager$Stub$Proxy cannot be cast to aidl.locationview.ILocationManager，
这个异常是由下面这行代码抛出的
mILocationManager = (ILocationManager) declaredField.get(mLocationManager);
请指点

**Comment by xiangtailiang** [comment]
mLocationManager 是一个AIDL接口的引用，它的类型是android.location.ILocationManager$Stub$Prox
